export type PluralCategory = 'zero' | 'one' | 'two' | 'few' | 'many' | 'other'

export type LocalizedMessage =
	| string
	| (Readonly<Partial<Record<PluralCategory, string>>> & {
			readonly other: string
	  })

export const englishCatalog = {
	'product.name': 'TrackMe',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Primary navigation',
	'navigation.today': 'Today',
	'navigation.week': 'Week',
	'navigation.month': 'Month',
	'navigation.projects': 'Projects',
	'actions.create': 'Create',
	'actions.openAppearance': 'Themes and language',
	'actions.close': 'Close',
	'window.controls': 'Window controls',
	'window.minimize': 'Minimize window',
	'window.maximize': 'Maximize window',
	'window.restore': 'Restore window',
	'window.close': 'Close window',
	'shell.greeting': 'Good day',
	'shell.focus': 'Today is not about doing everything, but moving what matters.',
	'filters.projects': 'All projects',
	'filters.tags': 'All tags',
	'board.label': 'Today task board',
	'task.status.todo': 'To do',
	'task.status.planned': 'Plan for today',
	'task.status.inProgress': 'In progress',
	'task.status.done': 'Done',
	'column.todo.note': 'when there is time',
	'column.planned.note': 'chosen for today',
	'column.inProgress.note': 'moving now',
	'column.done.note': 'time to exhale',
	'column.empty': 'Nothing here yet',
	'task.new': 'New task',
	'board.hiddenCompleted': {
		one: '{count} older completed task',
		other: '{count} older completed tasks'
	},
	'foundation.badge': 'Foundation ready',
	'foundation.storage': 'Local SQLite schema {version}',
	'foundation.description':
		'The secure application shell, local settings, themes and localization are connected.',
	'view.week.title': 'Your week',
	'view.week.description': 'Calendar planning arrives in the next product phase.',
	'view.month.title': 'Your month',
	'view.month.description': 'The monthly overview arrives in the next product phase.',
	'view.projects.title': 'Your projects',
	'view.projects.description': 'Project progress arrives after the task foundation.',
	'appearance.title': 'Themes and language',
	'appearance.description': 'Choose the atmosphere that helps you focus.',
	'appearance.themeFamily': 'Theme family',
	'appearance.colorMode': 'Color mode',
	'appearance.interfaceLanguage': 'Interface language',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description': 'Deep navy with cool glass and a soft glow',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Warm linen with a calm ink-blue accent',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description': 'Neutral smoky glass and restrained steel blue',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Soft indigo mist with a more creative character',
	'appearance.scheme.system': 'System',
	'appearance.scheme.light': 'Light',
	'appearance.scheme.dark': 'Dark',
	'appearance.locale.system': 'System',
	'appearance.locale.russian': 'Русский',
	'appearance.locale.english': 'English',
	'appearance.locale.spanish': 'Español',
	'errors.settings': 'TrackMe could not save this preference.',
	'menu.file': 'File',
	'menu.close': 'Close',
	'menu.quit': 'Quit TrackMe',
	'menu.view': 'View',
	'menu.reload': 'Reload',
	'menu.window': 'Window',
	'menu.minimize': 'Minimize'
} as const satisfies Readonly<Record<string, LocalizedMessage>>

export type LocalizationKey = keyof typeof englishCatalog
export type LocalizationCatalog = Readonly<Record<LocalizationKey, LocalizedMessage>>

export const russianCatalog = {
	'product.name': 'TrackMe',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Основная навигация',
	'navigation.today': 'Сегодня',
	'navigation.week': 'Неделя',
	'navigation.month': 'Месяц',
	'navigation.projects': 'Проекты',
	'actions.create': 'Создать',
	'actions.openAppearance': 'Темы и язык',
	'actions.close': 'Закрыть',
	'window.controls': 'Управление окном',
	'window.minimize': 'Свернуть окно',
	'window.maximize': 'Развернуть окно',
	'window.restore': 'Восстановить окно',
	'window.close': 'Закрыть окно',
	'shell.greeting': 'Добрый день',
	'shell.focus': 'Сегодня важно не успеть всё, а продвинуть главное.',
	'filters.projects': 'Все проекты',
	'filters.tags': 'Все теги',
	'board.label': 'Доска задач на сегодня',
	'task.status.todo': 'Входящие',
	'task.status.planned': 'На сегодня',
	'task.status.inProgress': 'В процессе',
	'task.status.done': 'Готово',
	'column.todo.note': 'когда будет время',
	'column.planned.note': 'выбрано на сегодня',
	'column.inProgress.note': 'двигается сейчас',
	'column.done.note': 'можно выдохнуть',
	'column.empty': 'Здесь пока ничего нет',
	'task.new': 'Новая задача',
	'board.hiddenCompleted': {
		one: '{count} старая завершённая задача',
		few: '{count} старые завершённые задачи',
		many: '{count} старых завершённых задач',
		other: '{count} старых завершённых задач'
	},
	'foundation.badge': 'Фундамент готов',
	'foundation.storage': 'Локальная схема SQLite {version}',
	'foundation.description':
		'Безопасная оболочка, локальные настройки, темы и локализация подключены.',
	'view.week.title': 'Ваша неделя',
	'view.week.description': 'Календарное планирование появится на следующем продуктовом этапе.',
	'view.month.title': 'Ваш месяц',
	'view.month.description': 'Месячный обзор появится на следующем продуктовом этапе.',
	'view.projects.title': 'Ваши проекты',
	'view.projects.description': 'Прогресс проектов появится после фундамента задач.',
	'appearance.title': 'Темы и язык',
	'appearance.description': 'Выберите атмосферу, которая помогает сосредоточиться.',
	'appearance.themeFamily': 'Семейство темы',
	'appearance.colorMode': 'Цветовой режим',
	'appearance.interfaceLanguage': 'Язык интерфейса',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description':
		'Глубокий тёмно-синий с прохладным стеклом и мягким сиянием',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Тёплый лён со спокойным чернильно-синим акцентом',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description':
		'Нейтральное дымчатое стекло и сдержанный стальной синий',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Мягкий туман индиго с более творческим характером',
	'appearance.scheme.system': 'Системный',
	'appearance.scheme.light': 'Светлый',
	'appearance.scheme.dark': 'Тёмный',
	'appearance.locale.system': 'Системный',
	'appearance.locale.russian': 'Русский',
	'appearance.locale.english': 'English',
	'appearance.locale.spanish': 'Español',
	'errors.settings': 'TrackMe не удалось сохранить эту настройку.',
	'menu.file': 'Файл',
	'menu.close': 'Закрыть',
	'menu.quit': 'Выйти из TrackMe',
	'menu.view': 'Вид',
	'menu.reload': 'Перезагрузить',
	'menu.window': 'Окно',
	'menu.minimize': 'Свернуть'
} as const satisfies LocalizationCatalog

export const spanishCatalog = {
	'product.name': 'TrackMe',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Navegación principal',
	'navigation.today': 'Hoy',
	'navigation.week': 'Semana',
	'navigation.month': 'Mes',
	'navigation.projects': 'Proyectos',
	'actions.create': 'Crear',
	'actions.openAppearance': 'Temas e idioma',
	'actions.close': 'Cerrar',
	'window.controls': 'Controles de ventana',
	'window.minimize': 'Minimizar ventana',
	'window.maximize': 'Maximizar ventana',
	'window.restore': 'Restaurar ventana',
	'window.close': 'Cerrar ventana',
	'shell.greeting': 'Buen día',
	'shell.focus': 'Hoy no se trata de hacerlo todo, sino de avanzar en lo importante.',
	'filters.projects': 'Todos los proyectos',
	'filters.tags': 'Todas las etiquetas',
	'board.label': 'Tablero de tareas de hoy',
	'task.status.todo': 'Pendientes',
	'task.status.planned': 'Plan para hoy',
	'task.status.inProgress': 'En curso',
	'task.status.done': 'Hecho',
	'column.todo.note': 'cuando haya tiempo',
	'column.planned.note': 'elegido para hoy',
	'column.inProgress.note': 'avanzando ahora',
	'column.done.note': 'momento de respirar',
	'column.empty': 'Todavía no hay nada aquí',
	'task.new': 'Nueva tarea',
	'board.hiddenCompleted': {
		one: '{count} tarea completada anterior',
		other: '{count} tareas completadas anteriores'
	},
	'foundation.badge': 'Base preparada',
	'foundation.storage': 'Esquema local de SQLite {version}',
	'foundation.description':
		'La interfaz segura, los ajustes locales, los temas y la localización están conectados.',
	'view.week.title': 'Tu semana',
	'view.week.description': 'La planificación del calendario llegará en la siguiente fase.',
	'view.month.title': 'Tu mes',
	'view.month.description': 'La vista mensual llegará en la siguiente fase.',
	'view.projects.title': 'Tus proyectos',
	'view.projects.description': 'El progreso de los proyectos llegará después de las tareas.',
	'appearance.title': 'Temas e idioma',
	'appearance.description': 'Elige la atmósfera que te ayuda a concentrarte.',
	'appearance.themeFamily': 'Familia del tema',
	'appearance.colorMode': 'Modo de color',
	'appearance.interfaceLanguage': 'Idioma de la interfaz',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description':
		'Azul marino profundo con cristal frío y un brillo suave',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Lino cálido con un tranquilo acento azul tinta',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description': 'Cristal ahumado neutro y azul acero discreto',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Suave niebla índigo con un carácter más creativo',
	'appearance.scheme.system': 'Sistema',
	'appearance.scheme.light': 'Claro',
	'appearance.scheme.dark': 'Oscuro',
	'appearance.locale.system': 'Sistema',
	'appearance.locale.russian': 'Русский',
	'appearance.locale.english': 'English',
	'appearance.locale.spanish': 'Español',
	'errors.settings': 'TrackMe no pudo guardar esta preferencia.',
	'menu.file': 'Archivo',
	'menu.close': 'Cerrar',
	'menu.quit': 'Salir de TrackMe',
	'menu.view': 'Ver',
	'menu.reload': 'Recargar',
	'menu.window': 'Ventana',
	'menu.minimize': 'Minimizar'
} as const satisfies LocalizationCatalog

export const catalogs = Object.freeze({
	en: englishCatalog,
	ru: russianCatalog,
	es: spanishCatalog
})
