export type PluralCategory = 'zero' | 'one' | 'two' | 'few' | 'many' | 'other'

export type LocalizedMessage =
	| string
	| (Readonly<Partial<Record<PluralCategory, string>>> & {
			readonly other: string
	  })

export const englishCatalog = {
	'product.name': 'TrackMe',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Primary navigation',
	'navigation.today': 'Today',
	'navigation.week': 'Week',
	'navigation.month': 'Month',
	'navigation.projects': 'Projects',
	'actions.create': 'Create',
	'actions.openAppearance': 'Themes and language',
	'actions.close': 'Close',
	'actions.save': 'Save',
	'actions.cancel': 'Cancel',
	'actions.archive': 'Archive',
	'actions.restore': 'Restore',
	'actions.retry': 'Try again',
	'actions.showAll': 'Show all',
	'actions.showRecent': 'Show recent',
	'actions.archived': 'Archived',
	'actions.editTask': 'Edit {title}',
	'actions.previousStatus': 'Move {title} to the previous status',
	'actions.nextStatus': 'Move {title} to the next status',
	'actions.clearFilters': 'Clear filters',
	'actions.newProject': 'New project',
	'actions.editProject': 'Edit project',
	'actions.saveProject': 'Save project',
	'window.controls': 'Window controls',
	'window.minimize': 'Minimize window',
	'window.maximize': 'Maximize window',
	'window.restore': 'Restore window',
	'window.close': 'Close window',
	'shell.greeting': 'Good day',
	'shell.focus': 'Today is not about doing everything, but moving what matters.',
	'filters.projects': 'All projects',
	'filters.tags': 'All tags',
	'filters.projectLabel': 'Filter by project',
	'filters.tagLabel': 'Filter by tag',
	'board.label': 'Today task board',
	'board.loading': 'Loading your tasks…',
	'board.loadError': 'TrackMe could not load the task board.',
	'board.filteredEmpty': 'No tasks match the current filters.',
	'board.dropHint': 'Drop a task here',
	'board.archivedDescription': 'Archived tasks stay safe and can be restored.',
	'task.status.todo': 'To do',
	'task.status.planned': 'Plan for today',
	'task.status.inProgress': 'In progress',
	'task.status.done': 'Done',
	'column.todo.note': 'when there is time',
	'column.planned.note': 'chosen for today',
	'column.inProgress.note': 'moving now',
	'column.done.note': 'time to exhale',
	'column.empty': 'Nothing here yet',
	'task.new': 'New task',
	'task.editor.createTitle': 'Create a task',
	'task.editor.editTitle': 'Edit task',
	'task.editor.description': 'Keep the essentials close and the next move clear.',
	'task.editor.discardConfirm': 'Discard the unsaved changes?',
	'task.field.title': 'Title',
	'task.field.description': 'Description',
	'task.field.status': 'Status',
	'task.field.estimate': 'Estimate in calendar days',
	'task.field.dueDate': 'Deadline',
	'task.field.startMode': 'Preferred start',
	'task.field.preferredStart': 'Manual start date',
	'task.field.project': 'Project',
	'task.field.tags': 'Tags',
	'task.placeholder.title': 'What needs to move forward?',
	'task.placeholder.description': 'Notes, context or useful links',
	'task.placeholder.tags': 'Focus, errands, work',
	'task.startMode.auto': 'Automatic',
	'task.startMode.manual': 'Manual',
	'task.autoStartHelp': 'Automatic start: {date}',
	'task.tagsHelp': 'Separate tags with commas. New names are created when the task is saved.',
	'task.project.none': 'No project',
	'task.estimate': {
		one: '{count} day',
		other: '{count} days'
	},
	'task.urgency.dueToday': 'Due today · {date}',
	'task.urgency.overdue': {
		one: '1 day overdue · {date}',
		other: '{count} days overdue · {date}'
	},
	'task.urgency.atRisk': {
		one: 'At risk · 1 day left · {date}',
		other: 'At risk · {count} days left · {date}'
	},
	'task.urgency.upcoming': {
		one: '1 day left · {date}',
		other: '{count} days left · {date}'
	},
	'task.urgency.completed': 'Completed · deadline {date}',
	'task.carried': 'Carried over from {date}',
	'task.validation.title': 'Enter a task title.',
	'task.validation.dueDate': 'Choose a deadline.',
	'task.validation.manualStart': 'Choose a manual start no later than the deadline.',
	'task.validation.conflict':
		'This task changed elsewhere. Reload the latest version before saving.',
	'task.validation.storageBusy': 'Local storage is busy. Wait a moment and try again.',
	'task.validation.generic': 'TrackMe could not save this task.',
	'task.archived.title': 'Archived tasks',
	'task.archived.empty': 'There are no archived tasks.',
	'project.editor.createTitle': 'Create project',
	'project.editor.editTitle': 'Edit project',
	'project.field.name': 'Project name',
	'project.field.description': 'Description and links',
	'project.validation.name': 'Enter a project name.',
	'project.validation.generic': 'TrackMe could not save this project.',
	'board.hiddenCompleted': {
		one: '{count} older completed task',
		other: '{count} older completed tasks'
	},
	'foundation.badge': 'Foundation ready',
	'foundation.storage': 'Local SQLite schema {version}',
	'foundation.description':
		'The secure application shell, local settings, themes and localization are connected.',
	'view.week.title': 'Your week',
	'view.week.description': 'Calendar planning arrives in the next product phase.',
	'view.month.title': 'Your month',
	'view.month.description': 'The monthly overview arrives in the next product phase.',
	'view.projects.title': 'Your projects',
	'view.projects.description': 'Project progress arrives after the task foundation.',
	'appearance.title': 'Themes and language',
	'appearance.description': 'Choose the atmosphere that helps you focus.',
	'appearance.themeFamily': 'Theme family',
	'appearance.colorMode': 'Color mode',
	'appearance.interfaceLanguage': 'Interface language',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description': 'Deep navy with cool glass and a soft glow',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Warm linen with a calm ink-blue accent',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description': 'Neutral smoky glass and restrained steel blue',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Soft indigo mist with a more creative character',
	'appearance.scheme.system': 'System',
	'appearance.scheme.light': 'Light',
	'appearance.scheme.dark': 'Dark',
	'appearance.locale.system': 'System',
	'appearance.locale.russian': 'Русский',
	'appearance.locale.english': 'English',
	'appearance.locale.spanish': 'Español',
	'errors.settings': 'TrackMe could not save this preference.',
	'menu.file': 'File',
	'menu.close': 'Close',
	'menu.quit': 'Quit TrackMe',
	'menu.view': 'View',
	'menu.reload': 'Reload',
	'menu.window': 'Window',
	'menu.minimize': 'Minimize'
} as const satisfies Readonly<Record<string, LocalizedMessage>>

export type LocalizationKey = keyof typeof englishCatalog
export type LocalizationCatalog = Readonly<Record<LocalizationKey, LocalizedMessage>>

export const russianCatalog = {
	'product.name': 'TrackMe',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Основная навигация',
	'navigation.today': 'Сегодня',
	'navigation.week': 'Неделя',
	'navigation.month': 'Месяц',
	'navigation.projects': 'Проекты',
	'actions.create': 'Создать',
	'actions.openAppearance': 'Темы и язык',
	'actions.close': 'Закрыть',
	'actions.save': 'Сохранить',
	'actions.cancel': 'Отмена',
	'actions.archive': 'Архивировать',
	'actions.restore': 'Восстановить',
	'actions.retry': 'Повторить',
	'actions.showAll': 'Показать все',
	'actions.showRecent': 'Показать недавние',
	'actions.archived': 'Архив',
	'actions.editTask': 'Изменить «{title}»',
	'actions.previousStatus': 'Переместить «{title}» в предыдущий статус',
	'actions.nextStatus': 'Переместить «{title}» в следующий статус',
	'actions.clearFilters': 'Сбросить фильтры',
	'actions.newProject': 'Новый проект',
	'actions.editProject': 'Изменить проект',
	'actions.saveProject': 'Сохранить проект',
	'window.controls': 'Управление окном',
	'window.minimize': 'Свернуть окно',
	'window.maximize': 'Развернуть окно',
	'window.restore': 'Восстановить окно',
	'window.close': 'Закрыть окно',
	'shell.greeting': 'Добрый день',
	'shell.focus': 'Сегодня важно не успеть всё, а продвинуть главное.',
	'filters.projects': 'Все проекты',
	'filters.tags': 'Все теги',
	'filters.projectLabel': 'Фильтр по проекту',
	'filters.tagLabel': 'Фильтр по тегу',
	'board.label': 'Доска задач на сегодня',
	'board.loading': 'Загружаем ваши задачи…',
	'board.loadError': 'TrackMe не удалось загрузить доску задач.',
	'board.filteredEmpty': 'Нет задач, подходящих под выбранные фильтры.',
	'board.dropHint': 'Перетащите задачу сюда',
	'board.archivedDescription': 'Архивные задачи сохранены, и их можно восстановить.',
	'task.status.todo': 'Входящие',
	'task.status.planned': 'На сегодня',
	'task.status.inProgress': 'В процессе',
	'task.status.done': 'Готово',
	'column.todo.note': 'когда будет время',
	'column.planned.note': 'выбрано на сегодня',
	'column.inProgress.note': 'двигается сейчас',
	'column.done.note': 'можно выдохнуть',
	'column.empty': 'Здесь пока ничего нет',
	'task.new': 'Новая задача',
	'task.editor.createTitle': 'Создать задачу',
	'task.editor.editTitle': 'Изменить задачу',
	'task.editor.description': 'Сохраните главное и сделайте следующий шаг ясным.',
	'task.editor.discardConfirm': 'Отказаться от несохранённых изменений?',
	'task.field.title': 'Название',
	'task.field.description': 'Описание',
	'task.field.status': 'Статус',
	'task.field.estimate': 'Оценка в календарных днях',
	'task.field.dueDate': 'Дедлайн',
	'task.field.startMode': 'Желательный старт',
	'task.field.preferredStart': 'Дата ручного старта',
	'task.field.project': 'Проект',
	'task.field.tags': 'Теги',
	'task.placeholder.title': 'Что нужно продвинуть?',
	'task.placeholder.description': 'Заметки, контекст или полезные ссылки',
	'task.placeholder.tags': 'Фокус, дела, работа',
	'task.startMode.auto': 'Автоматически',
	'task.startMode.manual': 'Вручную',
	'task.autoStartHelp': 'Автоматический старт: {date}',
	'task.tagsHelp': 'Разделяйте теги запятыми. Новые названия создадутся при сохранении.',
	'task.project.none': 'Без проекта',
	'task.estimate': {
		one: '{count} день',
		few: '{count} дня',
		many: '{count} дней',
		other: '{count} дня'
	},
	'task.urgency.dueToday': 'Срок сегодня · {date}',
	'task.urgency.overdue': {
		one: 'Просрочено на 1 день · {date}',
		few: 'Просрочено на {count} дня · {date}',
		many: 'Просрочено на {count} дней · {date}',
		other: 'Просрочено на {count} дня · {date}'
	},
	'task.urgency.atRisk': {
		one: 'В зоне риска · остался 1 день · {date}',
		few: 'В зоне риска · осталось {count} дня · {date}',
		many: 'В зоне риска · осталось {count} дней · {date}',
		other: 'В зоне риска · осталось {count} дня · {date}'
	},
	'task.urgency.upcoming': {
		one: 'Остался 1 день · {date}',
		few: 'Осталось {count} дня · {date}',
		many: 'Осталось {count} дней · {date}',
		other: 'Осталось {count} дня · {date}'
	},
	'task.urgency.completed': 'Завершено · дедлайн {date}',
	'task.carried': 'Перенесено с {date}',
	'task.validation.title': 'Введите название задачи.',
	'task.validation.dueDate': 'Выберите дедлайн.',
	'task.validation.manualStart': 'Выберите ручной старт не позже дедлайна.',
	'task.validation.conflict':
		'Задача изменилась в другом месте. Загрузите актуальную версию перед сохранением.',
	'task.validation.storageBusy': 'Локальное хранилище занято. Подождите немного и повторите.',
	'task.validation.generic': 'TrackMe не удалось сохранить задачу.',
	'task.archived.title': 'Архивные задачи',
	'task.archived.empty': 'Архивных задач пока нет.',
	'project.editor.createTitle': 'Создать проект',
	'project.editor.editTitle': 'Изменить проект',
	'project.field.name': 'Название проекта',
	'project.field.description': 'Описание и ссылки',
	'project.validation.name': 'Введите название проекта.',
	'project.validation.generic': 'TrackMe не удалось сохранить проект.',
	'board.hiddenCompleted': {
		one: '{count} старая завершённая задача',
		few: '{count} старые завершённые задачи',
		many: '{count} старых завершённых задач',
		other: '{count} старых завершённых задач'
	},
	'foundation.badge': 'Фундамент готов',
	'foundation.storage': 'Локальная схема SQLite {version}',
	'foundation.description':
		'Безопасная оболочка, локальные настройки, темы и локализация подключены.',
	'view.week.title': 'Ваша неделя',
	'view.week.description': 'Календарное планирование появится на следующем продуктовом этапе.',
	'view.month.title': 'Ваш месяц',
	'view.month.description': 'Месячный обзор появится на следующем продуктовом этапе.',
	'view.projects.title': 'Ваши проекты',
	'view.projects.description': 'Прогресс проектов появится после фундамента задач.',
	'appearance.title': 'Темы и язык',
	'appearance.description': 'Выберите атмосферу, которая помогает сосредоточиться.',
	'appearance.themeFamily': 'Семейство темы',
	'appearance.colorMode': 'Цветовой режим',
	'appearance.interfaceLanguage': 'Язык интерфейса',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description':
		'Глубокий тёмно-синий с прохладным стеклом и мягким сиянием',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Тёплый лён со спокойным чернильно-синим акцентом',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description':
		'Нейтральное дымчатое стекло и сдержанный стальной синий',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Мягкий туман индиго с более творческим характером',
	'appearance.scheme.system': 'Системный',
	'appearance.scheme.light': 'Светлый',
	'appearance.scheme.dark': 'Тёмный',
	'appearance.locale.system': 'Системный',
	'appearance.locale.russian': 'Русский',
	'appearance.locale.english': 'English',
	'appearance.locale.spanish': 'Español',
	'errors.settings': 'TrackMe не удалось сохранить эту настройку.',
	'menu.file': 'Файл',
	'menu.close': 'Закрыть',
	'menu.quit': 'Выйти из TrackMe',
	'menu.view': 'Вид',
	'menu.reload': 'Перезагрузить',
	'menu.window': 'Окно',
	'menu.minimize': 'Свернуть'
} as const satisfies LocalizationCatalog

export const spanishCatalog = {
	'product.name': 'TrackMe',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Navegación principal',
	'navigation.today': 'Hoy',
	'navigation.week': 'Semana',
	'navigation.month': 'Mes',
	'navigation.projects': 'Proyectos',
	'actions.create': 'Crear',
	'actions.openAppearance': 'Temas e idioma',
	'actions.close': 'Cerrar',
	'actions.save': 'Guardar',
	'actions.cancel': 'Cancelar',
	'actions.archive': 'Archivar',
	'actions.restore': 'Restaurar',
	'actions.retry': 'Intentar de nuevo',
	'actions.showAll': 'Mostrar todo',
	'actions.showRecent': 'Mostrar recientes',
	'actions.archived': 'Archivadas',
	'actions.editTask': 'Editar {title}',
	'actions.previousStatus': 'Mover {title} al estado anterior',
	'actions.nextStatus': 'Mover {title} al estado siguiente',
	'actions.clearFilters': 'Borrar filtros',
	'actions.newProject': 'Nuevo proyecto',
	'actions.editProject': 'Editar proyecto',
	'actions.saveProject': 'Guardar proyecto',
	'window.controls': 'Controles de ventana',
	'window.minimize': 'Minimizar ventana',
	'window.maximize': 'Maximizar ventana',
	'window.restore': 'Restaurar ventana',
	'window.close': 'Cerrar ventana',
	'shell.greeting': 'Buen día',
	'shell.focus': 'Hoy no se trata de hacerlo todo, sino de avanzar en lo importante.',
	'filters.projects': 'Todos los proyectos',
	'filters.tags': 'Todas las etiquetas',
	'filters.projectLabel': 'Filtrar por proyecto',
	'filters.tagLabel': 'Filtrar por etiqueta',
	'board.label': 'Tablero de tareas de hoy',
	'board.loading': 'Cargando tus tareas…',
	'board.loadError': 'TrackMe no pudo cargar el tablero de tareas.',
	'board.filteredEmpty': 'Ninguna tarea coincide con los filtros actuales.',
	'board.dropHint': 'Suelta una tarea aquí',
	'board.archivedDescription': 'Las tareas archivadas permanecen seguras y se pueden restaurar.',
	'task.status.todo': 'Pendientes',
	'task.status.planned': 'Plan para hoy',
	'task.status.inProgress': 'En curso',
	'task.status.done': 'Hecho',
	'column.todo.note': 'cuando haya tiempo',
	'column.planned.note': 'elegido para hoy',
	'column.inProgress.note': 'avanzando ahora',
	'column.done.note': 'momento de respirar',
	'column.empty': 'Todavía no hay nada aquí',
	'task.new': 'Nueva tarea',
	'task.editor.createTitle': 'Crear una tarea',
	'task.editor.editTitle': 'Editar tarea',
	'task.editor.description': 'Mantén lo esencial cerca y el siguiente paso claro.',
	'task.editor.discardConfirm': '¿Descartar los cambios sin guardar?',
	'task.field.title': 'Título',
	'task.field.description': 'Descripción',
	'task.field.status': 'Estado',
	'task.field.estimate': 'Estimación en días naturales',
	'task.field.dueDate': 'Fecha límite',
	'task.field.startMode': 'Inicio preferido',
	'task.field.preferredStart': 'Fecha de inicio manual',
	'task.field.project': 'Proyecto',
	'task.field.tags': 'Etiquetas',
	'task.placeholder.title': '¿Qué necesita avanzar?',
	'task.placeholder.description': 'Notas, contexto o enlaces útiles',
	'task.placeholder.tags': 'Enfoque, recados, trabajo',
	'task.startMode.auto': 'Automático',
	'task.startMode.manual': 'Manual',
	'task.autoStartHelp': 'Inicio automático: {date}',
	'task.tagsHelp': 'Separa las etiquetas con comas. Los nombres nuevos se crean al guardar.',
	'task.project.none': 'Sin proyecto',
	'task.estimate': {
		one: '{count} día',
		other: '{count} días'
	},
	'task.urgency.dueToday': 'Vence hoy · {date}',
	'task.urgency.overdue': {
		one: '1 día de retraso · {date}',
		other: '{count} días de retraso · {date}'
	},
	'task.urgency.atRisk': {
		one: 'En riesgo · queda 1 día · {date}',
		other: 'En riesgo · quedan {count} días · {date}'
	},
	'task.urgency.upcoming': {
		one: 'Queda 1 día · {date}',
		other: 'Quedan {count} días · {date}'
	},
	'task.urgency.completed': 'Completada · fecha límite {date}',
	'task.carried': 'Arrastrada desde {date}',
	'task.validation.title': 'Introduce un título para la tarea.',
	'task.validation.dueDate': 'Elige una fecha límite.',
	'task.validation.manualStart': 'Elige un inicio manual no posterior a la fecha límite.',
	'task.validation.conflict':
		'Esta tarea cambió en otro lugar. Carga la última versión antes de guardar.',
	'task.validation.storageBusy':
		'El almacenamiento local está ocupado. Espera un momento e inténtalo de nuevo.',
	'task.validation.generic': 'TrackMe no pudo guardar esta tarea.',
	'task.archived.title': 'Tareas archivadas',
	'task.archived.empty': 'No hay tareas archivadas.',
	'project.editor.createTitle': 'Crear proyecto',
	'project.editor.editTitle': 'Editar proyecto',
	'project.field.name': 'Nombre del proyecto',
	'project.field.description': 'Descripción y enlaces',
	'project.validation.name': 'Introduce un nombre para el proyecto.',
	'project.validation.generic': 'TrackMe no pudo guardar este proyecto.',
	'board.hiddenCompleted': {
		one: '{count} tarea completada anterior',
		other: '{count} tareas completadas anteriores'
	},
	'foundation.badge': 'Base preparada',
	'foundation.storage': 'Esquema local de SQLite {version}',
	'foundation.description':
		'La interfaz segura, los ajustes locales, los temas y la localización están conectados.',
	'view.week.title': 'Tu semana',
	'view.week.description': 'La planificación del calendario llegará en la siguiente fase.',
	'view.month.title': 'Tu mes',
	'view.month.description': 'La vista mensual llegará en la siguiente fase.',
	'view.projects.title': 'Tus proyectos',
	'view.projects.description': 'El progreso de los proyectos llegará después de las tareas.',
	'appearance.title': 'Temas e idioma',
	'appearance.description': 'Elige la atmósfera que te ayuda a concentrarte.',
	'appearance.themeFamily': 'Familia del tema',
	'appearance.colorMode': 'Modo de color',
	'appearance.interfaceLanguage': 'Idioma de la interfaz',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description':
		'Azul marino profundo con cristal frío y un brillo suave',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Lino cálido con un tranquilo acento azul tinta',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description': 'Cristal ahumado neutro y azul acero discreto',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Suave niebla índigo con un carácter más creativo',
	'appearance.scheme.system': 'Sistema',
	'appearance.scheme.light': 'Claro',
	'appearance.scheme.dark': 'Oscuro',
	'appearance.locale.system': 'Sistema',
	'appearance.locale.russian': 'Русский',
	'appearance.locale.english': 'English',
	'appearance.locale.spanish': 'Español',
	'errors.settings': 'TrackMe no pudo guardar esta preferencia.',
	'menu.file': 'Archivo',
	'menu.close': 'Cerrar',
	'menu.quit': 'Salir de TrackMe',
	'menu.view': 'Ver',
	'menu.reload': 'Recargar',
	'menu.window': 'Ventana',
	'menu.minimize': 'Minimizar'
} as const satisfies LocalizationCatalog

export const catalogs = Object.freeze({
	en: englishCatalog,
	ru: russianCatalog,
	es: spanishCatalog
})
