export type PluralCategory = 'zero' | 'one' | 'two' | 'few' | 'many' | 'other'

export type LocalizedMessage =
	| string
	| (Readonly<Partial<Record<PluralCategory, string>>> & {
			readonly other: string
	  })

export const englishCatalog = {
	'product.name': 'Tiempio',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Primary navigation',
	'navigation.today': 'Today',
	'navigation.week': 'Week',
	'navigation.month': 'Month',
	'navigation.projects': 'Projects',
	'actions.create': 'Create',
	'actions.openAppearance': 'Themes',
	'actions.openLanguage': 'Language settings',
	'actions.close': 'Close',
	'actions.save': 'Save',
	'actions.cancel': 'Cancel',
	'actions.archive': 'Archive',
	'actions.restore': 'Restore',
	'actions.retry': 'Try again',
	'actions.loadMore': 'Load more',
	'actions.showAll': 'Show all',
	'actions.showRecent': 'Show recent',
	'actions.archived': 'Archived',
	'actions.editTask': 'Edit {title}',
	'actions.previousStatus': 'Move {title} to the previous status',
	'actions.nextStatus': 'Move {title} to the next status',
	'actions.clearFilters': 'Clear filters',
	'actions.newProject': 'New project',
	'actions.editProject': 'Edit project',
	'actions.saveProject': 'Save project',
	'window.controls': 'Window controls',
	'window.minimize': 'Minimize window',
	'window.maximize': 'Maximize window',
	'window.restore': 'Restore window',
	'window.close': 'Close window',
	'shell.greeting': 'Good day',
	'shell.focus': 'Today is not about doing everything, but moving what matters.',
	'filters.projects': 'All projects',
	'filters.tags': 'All tags',
	'filters.projectLabel': 'Filter by project',
	'filters.tagLabel': 'Filter by tag',
	'board.label': 'Today task board',
	'board.loading': 'Loading your tasks…',
	'board.loadError': 'Tiempio could not load the task board.',
	'board.filteredEmpty': 'No tasks match the current filters.',
	'board.dropHint': 'Drop a task here',
	'board.archivedDescription': 'Archived tasks stay safe and can be restored.',
	'task.status.todo': 'To do',
	'task.status.planned': 'Plan for today',
	'task.status.inProgress': 'In progress',
	'task.status.done': 'Done',
	'column.empty': 'Nothing here yet',
	'task.new': 'New task',
	'task.editor.createTitle': 'Create a task',
	'task.editor.editTitle': 'Edit task',
	'task.editor.description': 'Add the details you need to know what to do and when.',
	'task.editor.discardTitle': 'Discard unsaved changes?',
	'task.editor.discardDescription':
		'The changes to this task have not been saved. If you leave now, they will be lost.',
	'task.editor.discardAction': 'Discard changes',
	'task.editor.continueEditing': 'Keep editing',
	'task.field.title': 'Title',
	'task.field.description': 'Description',
	'task.field.status': 'Status',
	'task.field.estimate': 'Estimate in calendar days',
	'task.field.dueDate': 'Deadline',
	'task.field.startMode': 'Preferred start',
	'task.field.preferredStart': 'Manual start date',
	'task.field.project': 'Project',
	'task.field.tags': 'Tags',
	'task.placeholder.title': 'What needs to be done?',
	'task.placeholder.description': 'Notes, context or useful links',
	'task.placeholder.tags': 'Focus, errands, work',
	'task.startMode.auto': 'Automatic',
	'task.startMode.manual': 'Manual',
	'task.autoStartHelp': 'Automatic start: {date}',
	'task.tagsHelp': 'Separate tags with commas. New names are created when the task is saved.',
	'task.tagsSuggestions': 'Existing tags',
	'task.project.none': 'No project',
	'task.estimate': {
		one: '{count} day',
		other: '{count} days'
	},
	'task.urgency.dueToday': 'Due today · {date}',
	'task.urgency.overdue': {
		one: '1 day overdue · {date}',
		other: '{count} days overdue · {date}'
	},
	'task.urgency.atRisk': {
		one: 'At risk · 1 day left · {date}',
		other: 'At risk · {count} days left · {date}'
	},
	'task.urgency.upcoming': {
		one: '1 day left · {date}',
		other: '{count} days left · {date}'
	},
	'task.urgency.completed': 'Completed · deadline {date}',
	'task.carried': 'Carried over from {date}',
	'task.validation.title': 'Enter a task title.',
	'task.validation.dueDate': 'Choose a deadline.',
	'task.validation.manualStart': 'Choose a manual start no later than the deadline.',
	'task.validation.conflict':
		'This task changed elsewhere. Choose which version you want to continue with.',
	'task.conflict.useLatest': 'Use latest version',
	'task.conflict.keepMine': 'Keep my changes',
	'task.validation.storageBusy': 'Local storage is busy. Wait a moment and try again.',
	'task.validation.generic': 'Tiempio could not save this task.',
	'task.archived.title': 'Archived tasks',
	'task.archived.empty': 'There are no archived tasks.',
	'project.editor.createTitle': 'Create project',
	'project.editor.editTitle': 'Edit project',
	'project.field.name': 'Project name',
	'project.field.description': 'Description and links',
	'project.validation.name': 'Enter a project name.',
	'project.validation.generic': 'Tiempio could not save this project.',
	'board.hiddenCompleted': {
		one: '{count} older completed task',
		other: '{count} older completed tasks'
	},
	'foundation.badge': 'Foundation ready',
	'foundation.storage': 'Local SQLite schema {version}',
	'foundation.description':
		'The secure application shell, local settings, themes and localization are connected.',
	'view.week.title': 'Your week',
	'view.week.description': 'Calendar planning arrives in the next product phase.',
	'view.month.title': 'Your month',
	'view.month.description': 'The monthly overview arrives in the next product phase.',
	'view.projects.title': 'Your projects',
	'view.projects.description': 'Project progress arrives after the task foundation.',
	'appearance.title': 'Themes',
	'appearance.description': 'Choose how Tiempio looks.',
	'appearance.themeFamily': 'Theme',
	'appearance.colorMode': 'Color mode',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description': 'Deep navy with cool glass and a soft glow',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Warm linen with a calm ink-blue accent',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description': 'Neutral smoky glass and restrained steel blue',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Soft indigo mist with a more creative character',
	'appearance.scheme.system': 'System',
	'appearance.scheme.light': 'Light',
	'appearance.scheme.dark': 'Dark',
	'language.action': 'Language',
	'language.title': 'Language',
	'language.description': 'Choose the language used throughout Tiempio.',
	'language.locale.system': 'Use system language',
	'language.locale.systemDescription': 'Match your device language when Tiempio supports it.',
	'language.locale.russian': 'Русский',
	'language.locale.russianDescription': 'Use Tiempio in Russian.',
	'language.locale.english': 'English',
	'language.locale.englishDescription': 'Use Tiempio in English.',
	'language.locale.spanish': 'Español',
	'language.locale.spanishDescription': 'Use Tiempio in Spanish.',
	'errors.settings': 'Tiempio could not save this preference.',
	'menu.file': 'File',
	'menu.close': 'Close',
	'menu.quit': 'Quit Tiempio',
	'menu.view': 'View',
	'menu.reload': 'Reload',
	'menu.window': 'Window',
	'menu.minimize': 'Minimize'
} as const satisfies Readonly<Record<string, LocalizedMessage>>

export type LocalizationKey = keyof typeof englishCatalog
export type LocalizationCatalog = Readonly<Record<LocalizationKey, LocalizedMessage>>

export const russianCatalog = {
	'product.name': 'Tiempio',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Основная навигация',
	'navigation.today': 'Сегодня',
	'navigation.week': 'Неделя',
	'navigation.month': 'Месяц',
	'navigation.projects': 'Проекты',
	'actions.create': 'Создать',
	'actions.openAppearance': 'Темы',
	'actions.openLanguage': 'Настройки языка',
	'actions.close': 'Закрыть',
	'actions.save': 'Сохранить',
	'actions.cancel': 'Отмена',
	'actions.archive': 'Архивировать',
	'actions.restore': 'Восстановить',
	'actions.retry': 'Повторить',
	'actions.loadMore': 'Загрузить ещё',
	'actions.showAll': 'Показать все',
	'actions.showRecent': 'Показать недавние',
	'actions.archived': 'Архив',
	'actions.editTask': 'Изменить «{title}»',
	'actions.previousStatus': 'Переместить «{title}» в предыдущий статус',
	'actions.nextStatus': 'Переместить «{title}» в следующий статус',
	'actions.clearFilters': 'Сбросить фильтры',
	'actions.newProject': 'Новый проект',
	'actions.editProject': 'Изменить проект',
	'actions.saveProject': 'Сохранить проект',
	'window.controls': 'Управление окном',
	'window.minimize': 'Свернуть окно',
	'window.maximize': 'Развернуть окно',
	'window.restore': 'Восстановить окно',
	'window.close': 'Закрыть окно',
	'shell.greeting': 'Добрый день',
	'shell.focus': 'Сегодня важнее сделать главное, чем успеть всё.',
	'filters.projects': 'Все проекты',
	'filters.tags': 'Все теги',
	'filters.projectLabel': 'Фильтр по проекту',
	'filters.tagLabel': 'Фильтр по тегу',
	'board.label': 'Доска задач на сегодня',
	'board.loading': 'Загружаем ваши задачи…',
	'board.loadError': 'Tiempio не удалось загрузить доску задач.',
	'board.filteredEmpty': 'Нет задач, подходящих под выбранные фильтры.',
	'board.dropHint': 'Перетащите задачу сюда',
	'board.archivedDescription': 'Задачи из архива можно восстановить в любой момент.',
	'task.status.todo': 'К выполнению',
	'task.status.planned': 'Запланировано на сегодня',
	'task.status.inProgress': 'В работе',
	'task.status.done': 'Готово',
	'column.empty': 'Здесь пока ничего нет',
	'task.new': 'Новая задача',
	'task.editor.createTitle': 'Создать задачу',
	'task.editor.editTitle': 'Изменить задачу',
	'task.editor.description': 'Добавьте основную информацию: что сделать и к какому сроку.',
	'task.editor.discardTitle': 'Не сохранять изменения?',
	'task.editor.discardDescription':
		'Изменения в задаче ещё не сохранены. Если выйти сейчас, они будут потеряны.',
	'task.editor.discardAction': 'Не сохранять',
	'task.editor.continueEditing': 'Продолжить редактирование',
	'task.field.title': 'Название',
	'task.field.description': 'Описание',
	'task.field.status': 'Статус',
	'task.field.estimate': 'Длительность (календарные дни)',
	'task.field.dueDate': 'Дедлайн',
	'task.field.startMode': 'Расчёт даты начала',
	'task.field.preferredStart': 'Дата начала',
	'task.field.project': 'Проект',
	'task.field.tags': 'Теги',
	'task.placeholder.title': 'Что нужно сделать?',
	'task.placeholder.description': 'Заметки, контекст или полезные ссылки',
	'task.placeholder.tags': 'важное, работа, покупки',
	'task.startMode.auto': 'Автоматически',
	'task.startMode.manual': 'Вручную',
	'task.autoStartHelp': 'Расчётная дата начала: {date}',
	'task.tagsHelp': 'Укажите теги через запятую. Новые теги создадутся при сохранении.',
	'task.tagsSuggestions': 'Добавить существующий тег',
	'task.project.none': 'Без проекта',
	'task.estimate': {
		one: '{count} день',
		few: '{count} дня',
		many: '{count} дней',
		other: '{count} дня'
	},
	'task.urgency.dueToday': 'Срок сегодня · {date}',
	'task.urgency.overdue': {
		one: 'Просрочено на 1 день · {date}',
		few: 'Просрочено на {count} дня · {date}',
		many: 'Просрочено на {count} дней · {date}',
		other: 'Просрочено на {count} дня · {date}'
	},
	'task.urgency.atRisk': {
		one: 'В зоне риска · остался 1 день · {date}',
		few: 'В зоне риска · осталось {count} дня · {date}',
		many: 'В зоне риска · осталось {count} дней · {date}',
		other: 'В зоне риска · осталось {count} дня · {date}'
	},
	'task.urgency.upcoming': {
		one: 'Остался 1 день · {date}',
		few: 'Осталось {count} дня · {date}',
		many: 'Осталось {count} дней · {date}',
		other: 'Осталось {count} дня · {date}'
	},
	'task.urgency.completed': 'Завершено · дедлайн {date}',
	'task.carried': 'Перенесено с {date}',
	'task.validation.title': 'Введите название задачи.',
	'task.validation.dueDate': 'Выберите дедлайн.',
	'task.validation.manualStart': 'Дата начала не может быть позже дедлайна.',
	'task.validation.conflict':
		'Задача была изменена в другом окне. Выберите, с какой версией продолжить работу.',
	'task.conflict.useLatest': 'Загрузить актуальную версию',
	'task.conflict.keepMine': 'Оставить мои изменения',
	'task.validation.storageBusy': 'Локальное хранилище занято. Подождите немного и повторите.',
	'task.validation.generic': 'Tiempio не удалось сохранить задачу.',
	'task.archived.title': 'Архивные задачи',
	'task.archived.empty': 'Архивных задач пока нет.',
	'project.editor.createTitle': 'Создать проект',
	'project.editor.editTitle': 'Изменить проект',
	'project.field.name': 'Название проекта',
	'project.field.description': 'Описание и ссылки',
	'project.validation.name': 'Введите название проекта.',
	'project.validation.generic': 'Tiempio не удалось сохранить проект.',
	'board.hiddenCompleted': {
		one: '{count} старая завершённая задача',
		few: '{count} старые завершённые задачи',
		many: '{count} старых завершённых задач',
		other: '{count} старых завершённых задач'
	},
	'foundation.badge': 'Фундамент готов',
	'foundation.storage': 'Локальная схема SQLite {version}',
	'foundation.description':
		'Безопасная оболочка, локальные настройки, темы и локализация подключены.',
	'view.week.title': 'Ваша неделя',
	'view.week.description': 'Календарное планирование появится на следующем продуктовом этапе.',
	'view.month.title': 'Ваш месяц',
	'view.month.description': 'Месячный обзор появится на следующем продуктовом этапе.',
	'view.projects.title': 'Ваши проекты',
	'view.projects.description': 'Прогресс проектов появится после фундамента задач.',
	'appearance.title': 'Темы',
	'appearance.description': 'Выберите оформление Tiempio.',
	'appearance.themeFamily': 'Тема',
	'appearance.colorMode': 'Светлое или тёмное оформление',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description':
		'Глубокий тёмно-синий с прохладным стеклом и мягким сиянием',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Тёплый лён со спокойным чернильно-синим акцентом',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description':
		'Нейтральное дымчатое стекло и сдержанный стальной синий',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Мягкий туман индиго с более творческим характером',
	'appearance.scheme.system': 'Системный',
	'appearance.scheme.light': 'Светлый',
	'appearance.scheme.dark': 'Тёмный',
	'language.action': 'Язык',
	'language.title': 'Язык интерфейса',
	'language.description': 'Выберите язык, на котором будет отображаться Tiempio.',
	'language.locale.system': 'Как в системе',
	'language.locale.systemDescription': 'Использовать язык устройства, если он поддерживается.',
	'language.locale.russian': 'Русский',
	'language.locale.russianDescription': 'Показывать интерфейс на русском языке.',
	'language.locale.english': 'English',
	'language.locale.englishDescription': 'Показывать интерфейс на английском языке.',
	'language.locale.spanish': 'Español',
	'language.locale.spanishDescription': 'Показывать интерфейс на испанском языке.',
	'errors.settings': 'Tiempio не удалось сохранить эту настройку.',
	'menu.file': 'Файл',
	'menu.close': 'Закрыть',
	'menu.quit': 'Выйти из Tiempio',
	'menu.view': 'Вид',
	'menu.reload': 'Перезагрузить',
	'menu.window': 'Окно',
	'menu.minimize': 'Свернуть'
} as const satisfies LocalizationCatalog

export const spanishCatalog = {
	'product.name': 'Tiempio',
	'product.tagline': 'Agile your life',
	'navigation.primary': 'Navegación principal',
	'navigation.today': 'Hoy',
	'navigation.week': 'Semana',
	'navigation.month': 'Mes',
	'navigation.projects': 'Proyectos',
	'actions.create': 'Crear',
	'actions.openAppearance': 'Temas',
	'actions.openLanguage': 'Ajustes de idioma',
	'actions.close': 'Cerrar',
	'actions.save': 'Guardar',
	'actions.cancel': 'Cancelar',
	'actions.archive': 'Archivar',
	'actions.restore': 'Restaurar',
	'actions.retry': 'Intentar de nuevo',
	'actions.loadMore': 'Cargar más',
	'actions.showAll': 'Mostrar todo',
	'actions.showRecent': 'Mostrar recientes',
	'actions.archived': 'Archivadas',
	'actions.editTask': 'Editar {title}',
	'actions.previousStatus': 'Mover {title} al estado anterior',
	'actions.nextStatus': 'Mover {title} al estado siguiente',
	'actions.clearFilters': 'Borrar filtros',
	'actions.newProject': 'Nuevo proyecto',
	'actions.editProject': 'Editar proyecto',
	'actions.saveProject': 'Guardar proyecto',
	'window.controls': 'Controles de ventana',
	'window.minimize': 'Minimizar ventana',
	'window.maximize': 'Maximizar ventana',
	'window.restore': 'Restaurar ventana',
	'window.close': 'Cerrar ventana',
	'shell.greeting': 'Buen día',
	'shell.focus': 'Hoy importa más avanzar en lo esencial que hacerlo todo.',
	'filters.projects': 'Todos los proyectos',
	'filters.tags': 'Todas las etiquetas',
	'filters.projectLabel': 'Filtrar por proyecto',
	'filters.tagLabel': 'Filtrar por etiqueta',
	'board.label': 'Tablero de tareas de hoy',
	'board.loading': 'Cargando tus tareas…',
	'board.loadError': 'Tiempio no pudo cargar el tablero de tareas.',
	'board.filteredEmpty': 'Ninguna tarea coincide con los filtros actuales.',
	'board.dropHint': 'Suelta una tarea aquí',
	'board.archivedDescription': 'Puedes restaurar las tareas archivadas en cualquier momento.',
	'task.status.todo': 'Por hacer',
	'task.status.planned': 'Para hoy',
	'task.status.inProgress': 'En progreso',
	'task.status.done': 'Completada',
	'column.empty': 'Todavía no hay nada aquí',
	'task.new': 'Nueva tarea',
	'task.editor.createTitle': 'Crear una tarea',
	'task.editor.editTitle': 'Editar tarea',
	'task.editor.description': 'Añade la información necesaria: qué hacer y para cuándo.',
	'task.editor.discardTitle': '¿Salir sin guardar los cambios?',
	'task.editor.discardDescription':
		'Los cambios de esta tarea aún no se han guardado. Si sales ahora, se perderán.',
	'task.editor.discardAction': 'Salir sin guardar',
	'task.editor.continueEditing': 'Seguir editando',
	'task.field.title': 'Título',
	'task.field.description': 'Descripción',
	'task.field.status': 'Estado',
	'task.field.estimate': 'Duración estimada (días naturales)',
	'task.field.dueDate': 'Fecha límite',
	'task.field.startMode': 'Cálculo de la fecha de inicio',
	'task.field.preferredStart': 'Fecha de inicio',
	'task.field.project': 'Proyecto',
	'task.field.tags': 'Etiquetas',
	'task.placeholder.title': '¿Qué hay que hacer?',
	'task.placeholder.description': 'Notas, contexto o enlaces útiles',
	'task.placeholder.tags': 'importante, trabajo, compras',
	'task.startMode.auto': 'Automático',
	'task.startMode.manual': 'Manual',
	'task.autoStartHelp': 'Fecha de inicio calculada: {date}',
	'task.tagsHelp': 'Separa las etiquetas con comas. Las nuevas se crearán al guardar.',
	'task.tagsSuggestions': 'Añadir una etiqueta existente',
	'task.project.none': 'Sin proyecto',
	'task.estimate': {
		one: '{count} día',
		other: '{count} días'
	},
	'task.urgency.dueToday': 'Vence hoy · {date}',
	'task.urgency.overdue': {
		one: '1 día de retraso · {date}',
		other: '{count} días de retraso · {date}'
	},
	'task.urgency.atRisk': {
		one: 'En riesgo · queda 1 día · {date}',
		other: 'En riesgo · quedan {count} días · {date}'
	},
	'task.urgency.upcoming': {
		one: 'Queda 1 día · {date}',
		other: 'Quedan {count} días · {date}'
	},
	'task.urgency.completed': 'Completada · fecha límite {date}',
	'task.carried': 'Pendiente desde {date}',
	'task.validation.title': 'Introduce un título para la tarea.',
	'task.validation.dueDate': 'Elige una fecha límite.',
	'task.validation.manualStart': 'La fecha de inicio no puede ser posterior a la fecha límite.',
	'task.validation.conflict':
		'Esta tarea cambió en otra ventana. Elige con qué versión quieres continuar.',
	'task.conflict.useLatest': 'Usar la versión actual',
	'task.conflict.keepMine': 'Conservar mis cambios',
	'task.validation.storageBusy':
		'El almacenamiento local está ocupado. Espera un momento e inténtalo de nuevo.',
	'task.validation.generic': 'Tiempio no pudo guardar esta tarea.',
	'task.archived.title': 'Tareas archivadas',
	'task.archived.empty': 'No hay tareas archivadas.',
	'project.editor.createTitle': 'Crear proyecto',
	'project.editor.editTitle': 'Editar proyecto',
	'project.field.name': 'Nombre del proyecto',
	'project.field.description': 'Descripción y enlaces',
	'project.validation.name': 'Introduce un nombre para el proyecto.',
	'project.validation.generic': 'Tiempio no pudo guardar este proyecto.',
	'board.hiddenCompleted': {
		one: '{count} tarea completada anterior',
		other: '{count} tareas completadas anteriores'
	},
	'foundation.badge': 'Base preparada',
	'foundation.storage': 'Esquema local de SQLite {version}',
	'foundation.description':
		'La interfaz segura, los ajustes locales, los temas y la localización están conectados.',
	'view.week.title': 'Tu semana',
	'view.week.description': 'La planificación del calendario llegará en la siguiente fase.',
	'view.month.title': 'Tu mes',
	'view.month.description': 'La vista mensual llegará en la siguiente fase.',
	'view.projects.title': 'Tus proyectos',
	'view.projects.description': 'El progreso de los proyectos llegará después de las tareas.',
	'appearance.title': 'Temas',
	'appearance.description': 'Elige el aspecto de Tiempio.',
	'appearance.themeFamily': 'Tema',
	'appearance.colorMode': 'Modo claro u oscuro',
	'appearance.theme.graphiteNavy.name': 'Graphite Navy',
	'appearance.theme.graphiteNavy.description':
		'Azul marino profundo con cristal frío y un brillo suave',
	'appearance.theme.linenBlue.name': 'Linen Blue',
	'appearance.theme.linenBlue.description': 'Lino cálido con un tranquilo acento azul tinta',
	'appearance.theme.pebbleSteel.name': 'Pebble Steel',
	'appearance.theme.pebbleSteel.description': 'Cristal ahumado neutro y azul acero discreto',
	'appearance.theme.fogIndigo.name': 'Fog Indigo',
	'appearance.theme.fogIndigo.description': 'Suave niebla índigo con un carácter más creativo',
	'appearance.scheme.system': 'Sistema',
	'appearance.scheme.light': 'Claro',
	'appearance.scheme.dark': 'Oscuro',
	'language.action': 'Idioma',
	'language.title': 'Idioma de la interfaz',
	'language.description': 'Elige el idioma que se usará en Tiempio.',
	'language.locale.system': 'Usar el idioma del sistema',
	'language.locale.systemDescription': 'Usar el idioma del dispositivo cuando Tiempio lo admita.',
	'language.locale.russian': 'Русский',
	'language.locale.russianDescription': 'Mostrar Tiempio en ruso.',
	'language.locale.english': 'English',
	'language.locale.englishDescription': 'Mostrar Tiempio en inglés.',
	'language.locale.spanish': 'Español',
	'language.locale.spanishDescription': 'Mostrar Tiempio en español.',
	'errors.settings': 'Tiempio no pudo guardar esta preferencia.',
	'menu.file': 'Archivo',
	'menu.close': 'Cerrar',
	'menu.quit': 'Salir de Tiempio',
	'menu.view': 'Ver',
	'menu.reload': 'Recargar',
	'menu.window': 'Ventana',
	'menu.minimize': 'Minimizar'
} as const satisfies LocalizationCatalog

export const catalogs = Object.freeze({
	en: englishCatalog,
	ru: russianCatalog,
	es: spanishCatalog
})
